name: No-IP Auto Renew

on:
  schedule:
    - cron: "35 11 * * 0"
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
      - name: Run No-IP Renewal
        env:
          NOIP_USERNAME: ${{ secrets.NOIP_USERNAME }}
          NOIP_PASSWORD: ${{ secrets.NOIP_PASSWORD }}
          NOIP_TOTP_SECRET: ${{ secrets.NOIP_TOTP_SECRET }}
        run: |
          mkdir -p ${{ github.workspace }}/screenshots
          docker run --rm -v ${{ github.workspace }}/screenshots:/app/screenshots kirbah/noip-renew:latest \
            -u "$NOIP_USERNAME" -p "$NOIP_PASSWORD" -s "$NOIP_TOTP_SECRET" -d DEBUG

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ${{ github.workspace }}/screenshots
          if-no-files-found: warn
